/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.amalia.praktikum;
import id.amalia.praktikum.scenes.LoginScene;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
 
public class App extends Application {
 
    @Override
    public void start(Stage stage) {
        stage.setTitle("Tugas Praktikum");
        stage.setResizable(false);
        Image  imageIcon = new Image(getClass().getResourceAsStream("/images/Logo.png"));
        stage.getIcons().add(imageIcon);
         
        VBox root = new VBox();
        Scene scene = new Scene(root, 840, 580);
        scene.getStylesheets().add(getClass().getResource("/styles/navbar.css").toExternalForm());
         
        stage.setScene(scene);
        stage.show();

        LoginScene loginScene = new LoginScene(stage);
        loginScene.show();
    }
    public static void main(String[] args) {
        launch();
    }
}